version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_app
    ports:
      - "3001:5000"  # Map port 5000 in the container to port 3000 on the host
    environment:
      - MONGO_HOST=mongodb  # Hostname for MongoDB service (same as the MongoDB container name)
      - MONGO_PORT=27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0  # Use the official MongoDB image (no Dockerfile needed)
    container_name: mongo_db
    ports:
      - "27017:27017"  # Expose MongoDB's default port
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

# Define a named volume for persisting MongoDB data
volumes:
  mongo-data: 
