apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: anitejsriv/flask-todo-app:v3
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongodb
            - name: MONGO_PORT
              value: "27017"
          livenessProbe:                   
            httpGet:
              path: /healthz               
              port: 5000
            initialDelaySeconds: 15        
            periodSeconds: 10             
            failureThreshold: 3            
          readinessProbe:                  
            httpGet:
              path: /ready                 
              port: 5000
            initialDelaySeconds: 5         
            periodSeconds: 5               
            failureThreshold: 3            