apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  containers:
    - name: flask-container
      image: anitejsriv/flask-todo-app:latest  # Replace with your Docker Hub image
      ports:
        - containerPort: 5000
      env:
        - name: MONGO_HOST
          value: mongodb  # MongoDB service hostname
        - name: MONGO_PORT
          value: "27017"
